version: '3.8'
services:
  coreservice:
    build:
      context: ./CoreService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - shared-network

  loanservice:
    build:
      context: ./LoanService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - shared-network

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
        - shared-network

networks:
  shared-network:
    external: true
