version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres-core:
    image: postgres:17
    container_name: postgres_core_db
    restart: always
    environment:
      POSTGRES_USER: coreuser
      POSTGRES_PASSWORD: corepassword
      POSTGRES_DB: coredb
    ports:
      - "5433:5432"
    volumes:
      - postgres_core_data:/var/lib/postgresql/data

  postgres-loan:
    image: postgres:17
    container_name: postgres_loan_db
    restart: always
    environment:
      POSTGRES_USER: loanuser
      POSTGRES_PASSWORD: loanpassword
      POSTGRES_DB: loandb
    ports:
      - "5434:5432"
    volumes:
      - postgres_loan_data:/var/lib/postgresql/data

  postgres-user:
    image: postgres:17
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: userdb
    ports:
      - "5435:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  coreservice:
    build:
      context: ./CoreService
    depends_on:
      - postgres-core
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres-core;Port=5432;Database=coredb;Username=coreuser;Password=corepassword

  loanservice:
    build:
      context: ./LoanService
    depends_on:
      - postgres-loan
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres-loan;Port=5432;Database=loandb;Username=loanuser;Password=loanpassword

  userservice:
    build:
      context: ./UserService
    depends_on:
      - postgres-user
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres-user;Port=5432;Database=userdb;Username=useruser;Password=userpassword

volumes:
  postgres_core_data:
  postgres_loan_data:
  postgres_user_data:
